### PR TITLE
Add custom, optional props for ScrollView

### PR DESCRIPTION
**Pull request by apperside**
Added new props to control the ScrollView's props, useful for example when you have to control things such as keyboardShouldPersistTaps

### CODE REVIEW

**Comment by enesozturk** [comment]
Hi @apperside Thanks for your contribution 🙌🏽 Looks like it is needed to pass scroll view props. I will check your PR as soon as possible.

**Comment by kelly-ry4n** [comment]
This is is awesome - I was just going to write an identical PR. 

Anything I can do to help get this merged?

**Comment by enesozturk** [comment]
Hi again. Sorry for delay. I merged your commits to the package. Thanks a lot for your contribution 🙌🏽 🥳

**Comment by kelly-ry4n** [comment]
Thank you! You the best!

**Comment by enesozturk** [comment]
You guys too 🔥

**Comment by apperside** [comment]
Amazing, thank you @enesozturk !

**Pull request merged**
